### PR TITLE
Create Scenarios of use

### PR DESCRIPTION
**Pull request by joeleden**
I added a file and got this message:

"You’re creating a file in a project you don’t have write access to. Submitting a change will create the file in a new branch in your fork joeleden/uiux, so you can send a pull request."

...being new to github I'm not really sure what the standard process is, so I'm trying this.

### CODE REVIEW

**Comment by dhimmel** [comment]
> being new to github I'm not really sure what the standard process is, so I'm trying this.

You did the correct thing by submitting the pull request. :+1: Congrats your first pull request.

@bdolly will have to decide whether he thinks this content is most appropriate as a file in this repository or the start of a GitHub issue discussion.

I suggest renaming `Scenarios of use` to `scenarios-of-use.md`. `.md` stands for [markdown](https://guides.github.com/features/mastering-markdown/), which will allow you to format your text. Also, you always want to have an extension on your filenames. If not `.md`, I'd recommend `.txt` for text.

**Comment by joeleden** [comment]
Ok, thanks.

I'm assuming it's best as a file given that we want to iterate on it, as opposed to an issue discussion...later iterations of these scenarios could be in storyboard format, where we'll have images along with text.

Thanks!
Joel

**Comment by dhimmel** [comment]
@joeleden would you like to rename the file to `scenarios-of-use.md` and apply some basic formatting so we can get this merged?

**Comment by joeleden** [comment]
Oh, I didn't realize I "must" do those things...github is finicky, huh :)

Ok, I'll try that.

**Comment by joeleden** [comment]
The .md format doesn't preserve line breaks, so after I tried that I changed it to .txt so at least the line breaks are there for now. I'll need to see what has to be done in .md format...it's just text for now, so I think .txt works for now.

**Comment by dhimmel** [comment]
> it's just text for now, so I think .txt works for now.

It will display in a much more readable way if we can get it to markdown.

I would suggest using lists and two-newlines for paragraph separation. For example:

``` md
Rough draft of scenarios based on post it notes from Oct 4th Cognoma meetup (Yianna serving as our cancer biologist subject matter expert):

Goal is to massage these into a human centered scenarios, editing as necessary, then “test” and iterate these with other cancer biologists.

## Scenario 1 (top row of post its):

+ It’s 10am on Tuesday, and Yianni is working at his bench.
+ He says hello to Cognoma.
+ Cognoma tells him the type of things he can help with.
+ Measure the impact of mutation in NFI.
```

**Comment by joeleden** [comment]
Yeah, I just don't like having to use markup for things like this...github
is obviously geared towards code, not so much for the types of artifacts
for design, etc...it seems visually distracting to me to have a bunch of
markup in there when editing...especially if I can't just put images in
there in place (I assuming I'll need to put a link to an image, rather than
be able to just place it inline)...even just Google drive/docs is a better
tool for this stuff, but I think you want all stuff in github. Maybe we can
use other tools and just link to them from github the way Ben has done with
the Invision prototype.

On Thu, Oct 6, 2016 at 5:07 PM, Daniel Himmelstein <notifications@github.com

**Comment by dhimmel** [comment]
> it seems visually distracting to me to have a bunch of markup in there when editing

The beauty of markdown is that it's readable as plain text. Since markdown does have a bit of a learning curve (although I do think it's valuable to learn), I applied the formatting for you.

**Comment by dhimmel** [comment]
@bdolly I'm going to merge this unless you say otherwise.

**Comment by bdolly** [comment]
@dhimmel I think this is good to merge for now. I do like @joeleden idea of using a Google Doc or something of that nature to collaborate on for this type of material. I think it could be handled the same way where an issue is created and left open in github as a reference to an external tool and then the issue get's updated if the reference changes just to keep all contributors to the project in the loop on updates and edits.

**Pull request merged**
