### PR TITLE
Added inVision App exports for Mutation and Sample Selection Prototype

### PR DESCRIPTION
**Pull request by bdolly**
clickable prototype located at https://invis.io/5P8PM61R8

### CODE REVIEW

**Comment by dhimmel** [comment]
@bdolly please wait to merge until you have an approval. Will try to prioritize this so you can get feedback with little delay

**Review by dhimmel — APPROVED** [review]
Really nice work. Love the latest version at https://projects.invisionapp.com/share/5P8PM61R8 looks a

**Comment by gwaybio** [comment]
@dhimmel @bdolly how are we doing on this pull request? Looks ready to merge to me!

**Comment by dhimmel** [comment]
@bdolly let's get your approved pull requests merged ASAP. You should do the merging as maintainer.

**Comment by bdolly** [comment]
@dhimmel I'll try and merge stuff in tonight, been slammed at work

**Pull request merged**
